/**
 * Chứa các tên action để dispatch cho reducer hoặc Saga
 */

/**
 ****** APP ACTIONS ******
 **/
export const APP = {
  PUSH_DATA_REGISTER : 'PUSH_DATA_REGISTER',
  CHECK_PHONE_START: 'CHECK_PHONE_START',
  CHECK_PHONE_ASYNC: 'CHECK_PHONE_ASYNC',
  CHECK_PHONE_END: 'CHECK_PHONE_END',

  REGISTER_START: 'REGISTER_START',
  REGISTER_ASYNC: 'REGISTER_ASYNC',
  REGISTER_END: 'REGISTER_END',

  PUSH_STATE_REGISTER: 'PUSH_STATE_REGISTER',

  GET_LIST_PROMOTION_START: 'GET_LIST_PROMOTION_START',
  GET_LIST_PROMOTION_ASYNC: 'GET_LIST_PROMOTION_ASYNC',
  GET_LIST_PROMOTION_END: 'GET_LIST_PROMOTION_END',

  CREATE_PROMOTION_START: 'CREATE_PROMOTION_START',
  CREATE_PROMOTION_ASYNC: 'CREATE_PROMOTION_ASYNC',
  CREATE_PROMOTION_END: 'CREATE_PROMOTION_END',

  GET_PROMOTION_BY_ID_START: 'GET_PROMOTION_BY_ID_START',
  GET_PROMOTION_BY_ID_ASYNC: 'GET_PROMOTION_BY_ID_ASYNC',
  GET_PROMOTION_BY_ID_END: 'GET_PROMOTION_BY_ID_END',

  LOGIN_START : 'LOGIN_START',
  LOGIN_ASYNC: 'LOGIN_ASYNC',
  LOGIN_END: 'LOGIN_END',

  GET_PROFILE_START: 'GET_PROFILE_START',
  GET_PROFILE_ASYNC: 'GET_PROFILE_ASYNC',
  GET_PROFILE_END: 'GET_PROFILE_END',

  GET_LIST_CUSTOMER_ALL_START: 'GET_LIST_CUSTOMER_ALL_START',
  GET_LIST_CUSTOMER_ALL_ASYNC: 'GET_LIST_CUSTOMER_ALL_ASYNC',
  GET_LIST_CUSTOMER_ALL_END: 'GET_LIST_CUSTOMER_ALL_END',

  GET_LIST_CUSTOMER_BY_STATUS_START: 'GET_LIST_CUSTOMER_BY_STATUS_START',
  GET_LIST_CUSTOMER_BY_STATUS_ASYNC: 'GET_LIST_CUSTOMER_BY_STATUS_ASYNC',
  GET_LIST_CUSTOMER_BY_STATUS_END: 'GET_LIST_CUSTOMER_BY_STATUS_END',

  GET_CUSTOMER_BY_ID_START: 'GET_CUSTOMER_BY_ID_START',
  GET_CUSTOMER_BY_ID_ASYNC: 'GET_CUSTOMER_BY_ID_ASYNC',
  GET_CUSTOMER_BY_ID_END: 'GET_CUSTOMER_BY_ID_END',

  UPDATE_STATUS_CUSTOMER_START: 'UPDATE_STATUS_CUSTOMER_START',
  UPDATE_STATUS_CUSTOMER_ASYNC: 'UPDATE_STATUS_CUSTOMER_ASYNC',
  UPDATE_STATUS_CUSTOMER_END: 'UPDATE_STATUS_CUSTOMER_END',

  GET_LIST_CONSTRUCTION_START: 'GET_LIST_CONSTRUCTION_START',
  GET_LIST_CONSTRUCTION_ASYNC: 'GET_LIST_CONSTRUCTION_ASYNC',
  GET_LIST_CONSTRUCTION_END: 'GET_LIST_CONSTRUCTION_END',

  GET_CONSTRUCTION_START: 'GET_CONSTRUCTION_START',
  GET_CONSTRUCTION_ASYNC: 'GET_CONSTRUCTION_ASYNC',
  GET_CONSTRUCTION_END: 'GET_CONSTRUCTION_END',

  UPDATE_STATUS_IMAGE_START: 'UPDATE_STATUS_IMAGE_START',
  UPDATE_STATUS_IMAGE_ASYNC: 'UPDATE_STATUS_IMAGE_ASYNC',
  UPDATE_STATUS_IMAGE_END: 'UPDATE_STATUS_IMAGE_END',

  UPDATE_STATUS_CONSTRUCTION_START : 'UPDATE_STATUS_CONSTRUCTION_START',
  UPDATE_STATUS_CONSTRUCTION_ASYNC : 'UPDATE_STATUS_CONSTRUCTION_ASYNC',
  UPDATE_STATUS_CONSTRUCTION_END : 'UPDATE_STATUS_CONSTRUCTION_END',

  UPDATE_CONSTRUCTION_START: 'UPDATE_CONSTRUCTION_START',
  UPDATE_CONSTRUCTION_ASYNC: 'UPDATE_CONSTRUCTION_ASYNC',
  UPDATE_CONSTRUCTION_END: 'UPDATE_CONSTRUCTION_END',

  GET_LIST_LABEL_START: 'GET_LIST_LABEL_START',
  GET_LIST_LABEL_ASYNC: 'GET_LIST_LABEL_ASYNC',
  GET_LIST_LABEL_END: 'GET_LIST_LABEL_END'


  
}
