/**
 * Chứa các tên action để dispatch cho reducer hoặc Saga
 */

/**
 ****** APP ACTIONS ******
 **/
export const APP = {
  PUSH_DATA_REGISTER : 'PUSH_DATA_REGISTER',
  CHECK_PHONE_START: 'CHECK_PHONE_START',
  CHECK_PHONE_ASYNC: 'CHECK_PHONE_ASYNC',
  CHECK_PHONE_END: 'CHECK_PHONE_END',

  REGISTER_START: 'REGISTER_START',
  REGISTER_ASYNC: 'REGISTER_ASYNC',
  REGISTER_END: 'REGISTER_END',

  PUSH_STATE_REGISTER: 'PUSH_STATE_REGISTER',

  GET_CUSTOMER_BY_ID_START: 'GET_CUSTOMER_BY_ID_START',
  GET_CUSTOMER_BY_ID_ASYNC: 'GET_CUSTOMER_BY_ID_ASYNC',
  GET_CUSTOMER_BY_ID_END: 'GET_CUSTOMER_BY_ID_END',

  GET_LIST_PROMOTION_START: 'GET_LIST_PROMOTION_START',
  GET_LIST_PROMOTION_ASYNC: 'GET_LIST_PROMOTION_ASYNC',
  GET_LIST_PROMOTION_END: 'GET_LIST_PROMOTION_END',

  CREATE_PROMOTION_START: 'CREATE_PROMOTION_START',
  CREATE_PROMOTION_ASYNC: 'CREATE_PROMOTION_ASYNC',
  CREATE_PROMOTION_END: 'CREATE_PROMOTION_END',

  GET_PROMOTION_BY_ID_START: 'GET_PROMOTION_BY_ID_START',
  GET_PROMOTION_BY_ID_ASYNC: 'GET_PROMOTION_BY_ID_ASYNC',
  GET_PROMOTION_BY_ID_END: 'GET_PROMOTION_BY_ID_END'

  
}
