/**
 * Chứa các tên action để dispatch cho reducer hoặc Saga
 */

/**
 ****** APP ACTIONS ******
 **/
export const APP = {
  PUSH_DATA_REGISTER : 'PUSH_DATA_REGISTER',
  CHECK_PHONE_START: 'CHECK_PHONE_START',
  CHECK_PHONE_ASYNC: 'CHECK_PHONE_ASYNC',
  CHECK_PHONE_END: 'CHECK_PHONE_END',

  REGISTER_START: 'REGISTER_START',
  REGISTER_ASYNC: 'REGISTER_ASYNC',
  REGISTER_END: 'REGISTER_END',

  PUSH_STATE_REGISTER: 'PUSH_STATE_REGISTER'

  
}
